name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃 중..
        uses: actions/checkout@v2

      - name: node 설치중..
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.2'

      - name: pnpm 설치중..
        run: npm install -g pnpm

      - name: 종속성 설치중...
        run: pnpm install
        working-directory: ./fe

      - name: 빌드 중..
        run: pnpm build
        working-directory: ./fe
