name: CI

on:
  pull_request:
    branches: [refactor/main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 레포지토리 체크아웃 중..
        uses: actions/checkout@v4 

      - name: node 설치중..
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.2'

      - name: 종속성 설치중...
        run: npm install
        working-directory: ./fe

      - name: 빌드 중..
        run: npm run build
        working-directory: ./fe

      # - name: 테스트 실행 중..
      #   run: npm run test
      #   working-directory: ./fe

      # - name: 코드 린트 체크 중..
      #   run: npm run lint
      #   working-directory: ./fe
